'use strict';

export const SET_ARTICLE_LIST = 'SET_ARTICLE_LIST';
export const SET_ARTICLE_DETAIL = 'SET_ARTICLE_DETAIL';
export const UPDATA_ACTIVE_SIDER_MENU = 'UPDATA_ACTIVE_SIDER_MENU';
export const UPDATA_ACTIVE_HEADER_MENU = 'UPDATA_ACTIVE_HEADER_MENU';
